language: python
dist: "xenial"
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -e .[test]

script:
  - python -m cone.tile.tests
  - coverage run --source src/cone/tile -m cone.tile.tests
  - coverage report

after_success:
  - coveralls
